### ISSUE TITLE
Font Spy calls callback too early when multiple fonts on an element

### ISSUE THREAD

**Issue by thisjustin** [patrickmarabeas/jQuery-FontSpy.js#3]
If you have an element with fonts like "OpenSansRegular, Helvetica, sans-serif" then FontSpy will call the callback the moment any of those load, which in the case of Helvetica / sans-serif is almost immediately. I would imagine that almost all the time you only really care about the first fonts you specify being loaded (in the example above, OpenSansRegular) so FontSpy should parse the font family CSS and only check the first font listed against comic sans to detect if the font has loaded.

**Comment by patrickmarabeas** [comment]
Thanks!
